### ISSUE TITLE
Files converted to GLTF/GLB have no color when opened in 3D Viewer

### ISSUE THREAD

**Issue by PolygonalSun** [BabylonJS/BabylonPolymorph#30]
When a file converted to .gltf/.glb is opened in 3D Viewer, the file appears to have no color.  When opened in the BJS Sandbox, the file looks correct.

**Comment by bghgary** [comment]
Do you have an example?

**Comment by PolygonalSun** [comment]
> Do you have an example?

Yes, but I can't share it publicly.  I can send you the files if you want to see them.

**Comment by PolygonalSun** [comment]
I've determined that this is an issue with 3D Viewer when trying to open files with a generator string that doesn't have a proper version for the Microsoft GLTF Exporter (from glTF-SDK)

**Comment by thomlucc** [comment]
Fixed
